export { quickAboutSchema } from "./quickAboutSchema"
export { servicesIntroSchema } from "./servicesIntroSchema"
export { testimonialsSchema } from "./testimonialsSchema"
export { gallerySchema } from "./gallerySchema"
export { recentProjectSchema } from "./recentProjectSchema"
export * from "./ourProcessSchema"
